### ISSUE TITLE
Unity 2018.2 scripts not open from Unity

### ISSUE THREAD

**Issue by dps999** [Unity-Technologies/vscode-unity-debug#100]
In Unity 2018.2 after double click on script it wouldn't appear in VS code. 
Just empty file appears

**Comment by KORJH** [comment]
All Script Not Open?

**Comment by miniwolf** [comment]
@dps999 So does the project that you have contain a white space? There is a known issue within Unity that VS Code will open i.e. "New Unity Project" as 4 files, "New", "Unity", "Project" and the last will be the actual file that you have specified "File.cs". If this is the case I can have a look when this issue is supposed to be out. I at least have fixed it for 18.3 and backported the fix to 18.2, but I do not know when it will be released.

**Comment by dps999** [comment]
Yes, my project has white spaces but only in the root folder.

**Comment by miniwolf** [comment]
If you remove the spaces the problem will go away. The problem will be fixed in upcoming patch of unity 18.2. But apparently not yet in the version you have.

**Comment by miniwolf** [comment]
This is not a VS Code issue, but a Unity issue.
