### ISSUE TITLE
What does it mean that this repo is no longer "officially supported"?

### ISSUE THREAD

**Issue by sanboxrunner** [Unity-Technologies/vscode-unity-debug#125]
Hiya, I use VSC for Unity for work. It greatly disturbs me that this debugger is no longer supported apparently? Can we get more of an explanation on that?

**Comment by miniwolf** [comment]
Some background story:
This product is the result of a conversion of the original extension https://github.com/Microsoft/vscode-mono-debug 
It was converted by an employee in Unity as a hobby/side project. Since then the extension has received some updates by both Unity employees and from the community. Though, Unity does not officially support the development of this product.

Does this mean developers at Unity might not work on maintenance or new features? No.
Does this mean that bugs will not be resolved? No.

What this mean is that there is distinction between products that are part of Unity, and external tools that people use for supporting the experience of working with Unity.

When a bug occurs in the  Unity product it goes through the QA process and has to get resolved and prioritized.
This process is not the same for this extension. Which is why there needs to be a distinction. 

When we can allocate some time to fix these problems, we will do so. But there is not the same guarantee, that things will work smoothly, and that bugs will be resolved within a certain time period as Unity does with bugs for the Unity product.

I hope this makes this more clear.

**Comment by sanboxrunner** [comment]
Okay, I can live with this!
