### ISSUE TITLE
Extension deprecated?

### ISSUE THREAD

**Issue by isidorn** [Unity-Technologies/vscode-unity-debug#206]
Isidor here from the VS Code team 👋 

We have noticed that you have not updated your extension for quite some time.
Do you plan to continue working on your extension? Do you feel like it is feature complete? Or is it deprecated? 
 
We have plans to introduce [deprecated extension](https://github.com/microsoft/vsmarketplace/issues/23) support to the Marketplace in the future and we want to better understand inactive extensions.
 
Thank you

**Comment by Morphexe** [comment]
User from the extensions and not an actual mantainer.

The current state is that its "usable" but in no way should be called  complete, its actually full of ugle bugs and caveats, and this repository seems to be unmaintained - as per usual from Unity Tech without any replies or feedback on it for years, sadly there is not current alternative to it out there.

**Comment by xoofx** [comment]
> Ok, so it is no longer maintained but functional. So we will most likely mark it as deprecated on our side. Users will still be able to use it and install it, but there will be a warning icon next to it.

Yes, thank you, it is indeed preferable to mark it deprecated until we have a better story about it. 

Our teams don't have the bandwidth/expertise to maintain this extension so we are in discussion with Microsoft .NET Teams to see what we can do about it, but nothing to share for now.

**Comment by isidorn** [comment]
Ok, so we will mark it as deprecated on the VS Code side.

**Comment by konistehrad** [comment]
As part of this effort, can you please annotate the [Unity page in the VSCode documentation](https://code.visualstudio.com/docs/other/unity)? Preferably with a banner at the top or the like explaining that these instructions are deprecated and should not be expected to work.

**Comment by isidorn** [comment]
@konistehrad thanks for the ping. I have opened this issue on our docs side to track this work https://github.com/microsoft/vscode-docs/issues/5360

**Comment by PyrateAkananto** [comment]
In our company many people use Unity together with Visual Studio Code. We really like Visual Studio Code because it is free 💰 , open source 👀, lightning fast 🚀 , fully supported by Microsoft 💪 and extended with plenty extensions 📦 . Without this specific extension there would be more more debugger and so we probably could not use it anymore for Unity development 😭 . Dear Visual Studio Code team: Please evaluate thoroughly whether you could take over the maintenance of this important extension.

**Comment by danieldownes** [comment]
Just the fact that it loads up so much quicker from Unity than VS does. Also VS Code has so many powerful extensions it easily surpasses VS in terms of features and usability. 

This VS Code need to be made the de-factor code editor for Unity. This extension just needs some continuous maintained. For example I am finding auto-complete is not working constantly, and in-line debug no longer works, which is critical for some development flows, especially in interactive application work like Unity.

Come on Unity, would rather my seat subscription money go into this than over anything I see in latest beta releases these days.

**Comment by konistehrad** [comment]
I should note that I strongly agree. VSCode provides a fast, powerful and consistent cross-platform experience that is vastly superior to alternatives on both Linux and Mac. While the Windows workflow may be "best" with Visual Studio Community I'm disappointed that this extremely helpful aspect of my Unity workflow is going away, and I hope that Unity can allocate resources to keeping it working.

**Comment by Cdddo** [comment]
Deprecated, really? So many Unity devs are using VSCode. How can Unity have tons of teams doing a million things, acquiring companies left and right, but not have enough developers to maintain something as essential as this? I moved my whole team from full Visual Studio because VSCode is so much faster and convenient. I do a lot of work with students, giving Unity courses, and VSCode is the best option for it being free and simple to setup, without the unnecessary bloat...

**Comment by isidorn** [comment]
Thanks for the feedback. However the VS Code team is not maintaining any of the extensions, we work on the core product and we make sure to design beautiful APIs so extensions can use this for their use cases.
It is up to Unity or somebody from the community to create and maintain an Unity extension for VS Code.

I can not comment for Unity the company since I work for Microsoft.

**Comment by xoofx** [comment]
We understand that VS Code is appreciated, but on Unity side, we have nobody allocated on maintaining this extension as it would require at least 3+ folks fulltime to do it. Both VS and Rider are fully supported commercial solutions and we advice our users to switch to these solutions.

We will announce the deprecation of these extensions (this one and the debugger). As this repository is provided with a permissive MIT license, it will be up to the community to fork it and maintain it.

**Comment by xoofx** [comment]
> Unity's intention to only support commercial, for-pay IDEs going forward?

Visual Studio Community is free and is supported with Unity. If you have narrow margins, that should be possible for you to use it.

Developing a good IDE experience requires lots of investments. That's what Microsoft/Visual Studio and JetBrains/Rider have been doing for years. Unlike our teams, they have the expertise and they have the funding. Developing and maintaining good software cost money. Same goes for games.

I'm personally monthly paying quite some money for many software I use. I do that because I want to value the work of others and I know how difficult it can be to live from software development.

**Comment by heckert-gamedev** [comment]
Has it occurred to you that VS-Code is pretty much required on Linux?

**Comment by xoofx** [comment]
> Has it occurred to you that VS-Code is pretty much required on Linux?

Rider is available on Linux.

**Comment by xoofx** [comment]
> The debugger extension as it is still "mostly works" even 2 years later of no one touching it, but crashes in certain circumstances (like Stepping Into certain code). It was made by one guy part-time. You need 2 part-timers at the most to occasionally update it.

You don't know the details of what it takes to maintain it, the dev processes that we need to follow internally, the multiple hacks that are required to overcome the limitations of the Mono debugger. The extension hasn't been updated for 2 years not because we didn't have anything to do but that we stopped developing on it because we had lots of other challenges on more critical parts of the engine.

**Comment by heckert-gamedev** [comment]
> > Has it occurred to you that VS-Code is pretty much required on Linux?
> 
> Rider is available on Linux.

Very funny. Are you going to pay it for me?

Which functionality is it we're going to lose, anyway?

**Comment by nanis94** [comment]
master

**Comment by VanIseghemThomas** [comment]
@xoofx any plans to reconsider this terrible decision, or anyone that has any workaround for the 2022 version?

**Comment by ChanceNCounter** [comment]
> You don't know the details of what it takes to maintain it, the dev processes that we need to follow internally, the multiple hacks that are required to overcome the limitations of the Mono debugger.

This is what you decided to leave for eternity as an answer to the devs who wander along?

That sort of “don’t speculate about my operations” attitude can make sense, but not when we’re talking about an IDE extension. The idea you’d need three full-timers for this suggests a willful incompetence that you don’t want to advertise to people who use your software to make our software.

**Comment by Morphexe** [comment]
Well, I do think you guys are being quite mean to someone, who probably cant do anything about the deprecation of the extension, he is a employee of a company - attacking a developer directly won`t make a difference.  This is a higher up decision from Unity.

Take this to the forums, and complain there.
I for one, don`t want to shell 120 for Rider yearly (would happily pay a 1 time fee though) but subscription models are a no go - especially since Unity is something I do for fun very occasionally - the trial period I had with rider I think I used it like 10 times, since I was busy - does not justify the price at all.

Clearly there is a gap, VSCODE is more active than ever and its actually a GREAT replacement for both of the options provided.

**Comment by ChanceNCounter** [comment]
xoofx is the Unity handle in charge of dotnet stuff, as I’ve understood it. I, too, would be annoyed by misdirected anger, but this is actually the person who would decide how much manpower to devote to this thing.

**Comment by Morphexe** [comment]
I stand corrected then, I though he was just a "random" developer. Still, pretty sure this is just not a 1 man decision. But, yeah he could have worded things slightly better.

**Comment by atorralb** [comment]
no wonder my vscode is not working... should make a stickin on the forum

**Comment by andybak** [comment]
The "3+ folks fulltime" estimate is either a huge exaggeration or Unity has some astonishingly dysfunctional processes. There's entire applications are developed and maintained with less people than that.
