### ISSUE TITLE
Debug State Seems Invalid

### ISSUE THREAD

**Issue by seesemichaelj** [Unity-Technologies/vscode-unity-debug#32]
A couple of weeks ago I noticed that the debugger within vscode was flawed. It would report that the threadpool broke/is stepping, but there would be no indicator of the line number which it was broken on, the variables window would be empty, and the debug console didn't think there was a stack frame.

Debugging within VS 2015 still works. The attached screenshot shows that I broke on the breakpoint shown and stepped once only to show the debugger is still not fully attached to the debug state.

![image](https://cloud.githubusercontent.com/assets/549323/24807575/bbcfd334-1b86-11e7-9b2f-339d10ececa3.png)

**Comment by juniordiscart** [comment]
Hey

I'm facing the same issue. In case some of the devs find time to investigate, please read my comment on this closed issue with an example project here: https://github.com/Unity-Technologies/vscode-unity-debug/issues/28

**Comment by miniwolf** [comment]
There is a new preview release which should have fixed this particular issue, if you would like to test it out please visit this post: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/

**Comment by miniwolf** [comment]
Closed due to inactivity. If this is still a problem, please submit a new comment.

**Comment by Andres-NG** [comment]
This seems to be happening still. VSCode 1.43.1, C# extension 1.21.15 and Debugger for Unity 2.7.5. I think this may have something to do with reflection being used to call the methods with breakpoints.

**Comment by miniwolf** [comment]
@Andres-NG do you have a small repo case that I can use for testing?

**Comment by Andres-NG** [comment]
Well I can explain where it happens (doesn't happen in every case) but basically, we have a debug menu within our game, where all the debug code is in blocks like this:
```
#if DEBUG_COMMANDS
[DebugMenu]
private void DebugFunction()
{
    MethodThatHasBreakpoint()
}
#endif

private void MethodThatHasBreakpoint()
{
    foo() // this has a breakpoint
    bar()
}
```



We use reflection to find all the methods that have the DebugMenu attribute on them and add them to a debug UI, and call them once input is given through that UI.

That is the code that will not trigger breakpoints (though the breakpoints themselves are not within those DEBUG_COMMANDS blocks. Hope this helps, since I cannot share our code base.

Then in Unity we have the preprocessor directive added in the player settings.

**Comment by miniwolf** [comment]
So this is like `[MenuItem(String s)]` in Unity. But thanks I will add that case to my list of things to test for the new release.
