### ISSUE TITLE
Conditional Breakpoints not supported

### ISSUE THREAD

**Issue by AlejandroHuerta** [Unity-Technologies/vscode-unity-debug#46]
I'm not sure if this is an issue with this extension or with the C# extension. I'm using Unity 5.4.3f1 and when I try to set a conditional breakout I get `Conditional breakpoints not supported by this debug type`

**Comment by CorneliaXaos** [comment]
This is honestly, I feel, more of a bug than an enhancement.  As someone who cannot use Visual Studio Community (I develop on Linux) this feels more like a regression since the deprecation of MonoDevelop.  It is seriously a task to debug a loop that may execute hundreds of times but errors on an edge case, and you need to break precisely then so you can determine what's going on.

**Comment by ivanarellano** [comment]
I received this issue too when adding a conditional breakpoint. My setup: Debugger For Unity 1.3.0, VSCode 1.21.1 (1.21.1), Unity 2017.4.0f1, Mac 10.13.3.

**Comment by miniwolf** [comment]
There is a new preview release which should have fixed this particular issue, if you would like to test it out please visit this post: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/
