### ISSUE TITLE
[.NET 4.6] Breakpoints and hovering aren't working on the new runtime

### ISSUE THREAD

**Issue by PoisonousJohn** [Unity-Technologies/vscode-unity-debug#51]
With the Unity 2017.1.0f3 and VSCode  1.15.0 I have following issues:

- Breakpoints are not set upon start and not working until your reset them manually
- Hovering variables gives "not available" error. I'm assuming that current frame info is not passed correctly to the debugger.

I checked that breakpoints issue reproduces only with 4.x runtime. Hovering seems to be working on the old runtime too

**Comment by Bebop182** [comment]
I'm running Unity 2017.1.0f3 and latest VSCode 1.15.1
I have the exact same issue as you: Unity won't stop on breakpoint.
However I can get it to work when I switch the scripting runtime version to 4.6 experimental in the unity player settings.
So breakpoints don't work for me on .Net 3.5 stable since last unity update.
Although it is working with 4.6 exp, stopping debugging from VS code while paused on a step will result in Unity process dead locking, with no other way out than killing the process.

**Comment by dps999** [comment]
The same here. Sometimes not stop on a breakpoint

**Comment by miniwolf** [comment]
There is a new preview release which should have fixed this particular issue, if you would like to test it out please visit this post: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/
