### ISSUE TITLE
Debug mode pause script. only pause one thread 

### ISSUE THREAD

**Issue by fjqingyou** [Unity-Technologies/vscode-unity-debug#87]
OS: Mac os Sierra 10.12.6
VSCode  1.23.1 (1.23.1)
Debugger for Unity 2.5.0
Mono Debug 0.15.8

Debug mode pause script. only pause one thread ,

but ,this thread it's is from  using code create new Thread(...)

I didn't find the main thread and I can't pause other threads

![qq20180529-144831](https://user-images.githubusercontent.com/31087168/40642457-c00afb10-634f-11e8-8668-462ae07b7efe.png)

**Comment by miniwolf** [comment]
From what I can see it is pausing all threads. I have both the main thread (Thread #1) and the child thread (ChildProcess) which I created using `new Thread(threadStart)` as you can see in the code. The output is paused correctly. And I can enter debugging in the thread. Though I don't know why it is still saying "running" because it is not. I cannot interact with Unity at the time of breakpoint within the child process.
![image](https://user-images.githubusercontent.com/710238/40713328-f8e2aa18-63ff-11e8-9b61-3d10a4275727.png)

**Comment by fjqingyou** [comment]
@miniwolf 

In the case of a thread pause, can you freely switch to other threads created by yourself using C#?

**Comment by miniwolf** [comment]
No I get what you mean. The stack trace are not being expanded on all threads. I will investigate how that is possible.

**Comment by fjqingyou** [comment]
@miniwolf 
Yes, it's!  Thanks!

**Comment by miniwolf** [comment]
I have added a new release that should solve this:  https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/
I hope this helps

**Comment by fjqingyou** [comment]
@miniwolf 
I'm install this unity-debug-2.6.0.vsix

This problem has been solved, so i'm close this issue. Thank you!
